# Tcl script generated by PlanAhead

set reloadAllCoreGenRepositories false

set tclUtilsPath "c:/Xilinx/14.5/ISE_DS/PlanAhead/scripts/pa_cg_utils.tcl"

set repoPaths ""

set cgIndexMapPath "C:/local/local_copy/novena-gpbb/novena-gpbb.srcs/sources_1/ip/cg_nt_index_map.xml"

set cgProjectPath "c:/local/local_copy/novena-gpbb/novena-gpbb.srcs/sources_1/ip/clk_dll/coregen.cgc"

set ipFile "c:/local/local_copy/novena-gpbb/novena-gpbb.srcs/sources_1/ip/clk_dll/clk_dll.xco"

set ipName "clk_dll"

set chains "CUSTOMIZE_CURRENT_CHAIN INSTANTIATION_TEMPLATES_CHAIN"

set bomFilePath "c:/local/local_copy/novena-gpbb/novena-gpbb.srcs/sources_1/ip/clk_dll/pa_cg_bom.xml"

set cgPartSpec "xc6slx45-3csg324"

set hdlType "Verilog"

# generate the IP
set result [source "c:/Xilinx/14.5/ISE_DS/PlanAhead/scripts/pa_cg_reconfig_core.tcl"]

exit $result

